"""initial migration

Revision ID: 70aa044d62b0
Revises: 
Create Date: 2024-11-28 22:32:18.162914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aa044d62b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adding_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_numbers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_numbers')
    # ### end Alembic commands ###
