"""add value

Revision ID: e167f38dd705
Revises: 70aa044d62b0
Create Date: 2024-11-28 22:46:26.445550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e167f38dd705'
down_revision = '70aa044d62b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_numbers', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
